import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProviders from "@/providers/AuthProviders";
import StoreProvider from "@/providers/StoreProvider";
import QueryClientProviderLocal from "@/provider/QueryClientProviderLocal";
import { AlertProvider } from "@/components/AlertPopUp/AlertPopup";
import { ModalProvider } from "@/components/shared/modal";
import GlobalModal from "@/components/shared/modal/GlobalModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <StoreProvider>
          <AuthProviders>
            <QueryClientProviderLocal>
              <AlertProvider>
                <ModalProvider>
                  {children}
                  <GlobalModal />
                </ModalProvider>
              </AlertProvider>
            </QueryClientProviderLocal>
          </AuthProviders>
        </StoreProvider>
      </body>
    </html>
  );
}
